import Head from 'next/head';
import { Title, CodeTag } from '../components/sharedstyles';
import Cards from '../components/cards';
import { getAll, UserType } from '../data/user';
import styled from 'styled-components';
import { NextPage } from 'next';
import UserCard from '../components/UserCard';
import { useState } from 'react';

const Home: NextPage<{ users: UserType[] }> = ({ users }) => {
	const [searchString, setSearchString] = useState('second');

	const filteredUsers = users.filter((user) => {
		const fullName = user.firstName + user.lastName;

		return searchString === ''
			? true
			: fullName.toLowerCase().includes(searchString.toLowerCase());
	});

	return (
		<Container>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Title>
				Welcome <span>Admin!</span>
			</Title>

			<SearchWithIcon>
				<SearchInput
					type="text"
					placeholder="mitarbeiter suchen"
					onChange={(e) => {
						setSearchString(e.target.value);
					}}
				/>
				<span>&#128269;</span>
			</SearchWithIcon>

			<UsersContainer>
				{filteredUsers.map((user) => (
					<UserCard {...user} />
				))}
			</UsersContainer>

			<Cards />
		</Container>
	);
};

export default Home;

export async function getStaticProps() {
	const users = await getAll();
	return {
		props: {
			users,
		},
	};
}

const Container = styled.div`
	max-width: 875px;
	margin: 0 auto;
`;
const UsersContainer = styled.div`
	display: grid;
	grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
	gap: 1rem;
`;
const SearchWithIcon = styled.div`
	position: relative;
	margin-bottom: 1rem;
	max-width: 302px;
	span {
		position: absolute;
		right: 0.5rem;
	}
`;

const SearchInput = styled.input`
	padding: 0.5rem;
	border-radius: 0.5rem;
	border: 1px solid #ebebeb;
	margin-bottom: 1rem;
	width: 100%;
`;
