import Head from 'next/head';
import { useRouter } from 'next/router';
import styled from 'styled-components';
import Footer from './Footer';
import Header from './Header';

const Layout = ({ children }) => {
	const router = useRouter();

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />

				<meta name="application-name" content="PWA App" />
				<meta name="apple-mobile-web-app-capable" content="yes" />
				<meta name="apple-mobile-web-app-status-bar-style" content="default" />
				<meta name="apple-mobile-web-app-title" content="PWA App" />
				<meta name="description" content="Best PWA App in the world" />
				<meta name="format-detection" content="telephone=no" />
				<meta name="mobile-web-app-capable" content="yes" />
				<meta name="msapplication-config" content="/icons/browserconfig.xml" />
				<meta name="msapplication-TileColor" content="#2B5797" />
				<meta name="msapplication-tap-highlight" content="no" />
				<meta name="theme-color" content="#000000" />

				<link rel="apple-touch-icon" href="/icons/touch-icon-iphone.png" />
				<link
					rel="apple-touch-icon"
					sizes="152x152"
					href="/icons/touch-icon-ipad.png"
				/>
				<link
					rel="apple-touch-icon"
					sizes="180x180"
					href="/icons/touch-icon-iphone-retina.png"
				/>
				<link
					rel="apple-touch-icon"
					sizes="167x167"
					href="/icons/touch-icon-ipad-retina.png"
				/>

				<link
					rel="icon"
					type="image/png"
					sizes="32x32"
					href="/icons/favicon-32x32.png"
				/>
				<link
					rel="icon"
					type="image/png"
					sizes="16x16"
					href="/icons/favicon-16x16.png"
				/>
				<link rel="manifest" href="/manifest.json" />
				<link
					rel="mask-icon"
					href="/icons/safari-pinned-tab.svg"
					color="#5bbad5"
				/>
				<link rel="shortcut icon" href="/favicon.ico" />
				<link
					rel="stylesheet"
					href="https://fonts.googleapis.com/css?family=Roboto:300,400,500"
				/>

				<meta name="twitter:card" content="summary" />
				<meta name="twitter:url" content="https://yourdomain.com" />
				<meta name="twitter:title" content="PWA App" />
				<meta name="twitter:description" content="Best PWA App in the world" />
				<meta
					name="twitter:image"
					content="https://yourdomain.com/icons/android-chrome-192x192.png"
				/>
				<meta name="twitter:creator" content="@DavidWShadow" />
				<meta property="og:type" content="website" />
				<meta property="og:title" content="PWA App" />
				<meta property="og:description" content="Best PWA App in the world" />
				<meta property="og:site_name" content="PWA App" />
				<meta property="og:url" content="https://yourdomain.com" />
				<meta
					property="og:image"
					content="https://yourdomain.com/icons/apple-touch-icon.png"
				/>
				<link
					rel="stylesheet"
					href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css"
					integrity="sha512-1cK78a1o+ht2JcaW6g8OXYwqpev9+6GqOkz9xmBN9iUUhIndKtxwILGWYOSibOKjLsEdjyjZvYDq/cZwNeak0w=="
					crossOrigin="anonymous"
					referrerPolicy="no-referrer"
				/>
				<script
					src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.js"
					integrity="sha512-A7AYk1fGKX6S2SsHywmPkrnzTZHrgiVT7GcQkLGDe2ev0aWb8zejytzS8wjo7PGEXKqJOrjQ4oORtnimIRZBtw=="
					crossOrigin="anonymous"
					referrerPolicy="no-referrer"></script>
				<script>AOS.init();</script>
			</Head>
			<Header pathName={router.pathname} />
			<Main>{children}</Main>
			{/* <Footer /> */}
		</>
	);
};

export default Layout;
const Main = styled.main`
	min-height: 80vh;
`;
